### ISSUE TITLE
Where is the text from. Has it been validated.

### ISSUE THREAD

**Issue by husayt** [islamic-network/api.alquran.cloud#19]
It has been asked from me and I looked through the website. But nowhere I could find where it mentions the source of Quran text. Taking into account the sensitivity of this matter, it is essential to provide source information on every single text of Holy Quran present in the Db (simple, Uthmani, tajweed and etc). Who has verified the text is what I have been asked many times.

Thanks

**Comment by meezaan** [comment]
Al Salaamu Alaykum,

All the text comes from GlobalQuran.com as mentioned on https://alquran.cloud/contributors which ultimately comes from Tanzil.net (http://tanzil.net/docs/). See https://github.com/GlobalQuran/site/issues/33 for a similar answer.

Also see http://tanzil.net/docs/credits - this will give you names of the verifiers.

Hope this helps.

**Comment by meezaan** [comment]
I've added Tanzil.net to the Contributors page. https://github.com/islamic-network/alquran.cloud/commit/5fb609eae5ab3a05498545fb744415fab7f5f075

**Comment by husayt** [comment]
Thank you very much for claryfiying. Seems tanzil.net itself going through some problems. Download page ignores all the parameters (e.g. small alef and etc) and always returns the same text. I tried to contact them, but seems contact page is also broken. That is why having reliable alternatives is very important. 

Thanks for this work. JZKH

**Comment by meezaan** [comment]
Most open source projects end up suffering from these kind of issues because the community doesn't always support them.

In any case, validation of the text is always a contestable matter for the skeptic and can always be questioned depending on the background of a person and the 'criteria' he / she adheres to.

It's certainly not something I would discuss as a software engineer with anyone in any way more than a citation (which in this case is tanzil.net).
