### ISSUE TITLE
Issues with Quran words that has Alef with Hamza like "وَبِٱلْءَاخِرَةِ هُمْ" , "وَبِٱلْيَوْمِ ٱلْءَاخِرِ" 

### ISSUE THREAD

**Issue by vipafattal** [islamic-network/api.alquran.cloud#31]
I always thought these issues are related fonts and I tried many different fonts, but it turns out it's an issue from the data that's received from the API using `quran-uthmani` edition. Even though some fonts like me_quran & Amiri are showing without any issues, but when copying from the Quranic text the issues become visible [please see](https://github.com/vipafattal/Mushaf/issues/7#issue-577501423).

**Comment by meezaan** [comment]
Salaam brother.

So this is interesting. Grammatically, the text appears correctly and the alif needs go after the Hamza.  But for the Qur'an it is written differently where the hamza is just placed before the alif when the laam and alif are joined - so this is intelligence that needs to be baked into the font, which is why some of them display it properly.

ءَا in that order are a different pronunciation and meaning from أَ  so I don't think the API would or should serve text that way.

I will do some more research on the issue, at least grammatically and linguistically, insha Allah.

**Comment by vipafattal** [comment]
Salaam brother @meezaan 

I've got your point but must of the fonts don't support this case and they don't have that intelligence so they turn out to make an issue when using them with `quran-uthmani`.

**Comment by meezaan** [comment]
Alaykum Salaam brother and Mabruk on your app.

In your view, would it be better to create a new edition to accommodate fonts or simply create an official font for Qur'anic text that solves the problem?

**Comment by vipafattal** [comment]
All credits go for your support thanks @meezaan 

Creating a new edition will solve this problem.

**Comment by vipafattal** [comment]
Salaam Alaykum, 
Any news about thi issue.

Thanks brother

**Comment by meezaan** [comment]
Salaam brother, no, unfortunately there has not been progress - simply have not had the time. I do want to try out this font too https://quranacademy.gitbook.io/digital-quran/content-and-release-plan/font-kitab as I think it will solve the display issue.

I understand the issue has some urgency because it impacts the app, would you be able to create it and share the SQL dump?

I will leave open this issue and leave it re-opened - otherwise it will completely fall off my radar.

**Comment by vipafattal** [comment]
Thank you @meezaan,
Sorry, I couldn't understand what do mean by SQL dump

**Comment by vipafattal** [comment]
I will also test the font.

**Comment by vipafattal** [comment]
Using [Kitab-Regular.ttf](https://github.com/quranacademy/kitab-font/blob/master/Kitab-Regular.ttf) the font is very neat, but unfortunately the same issue with "ٱلْءَاخِرِ" see the screenshot:
![Screenshot_1589116733](https://user-images.githubusercontent.com/22567094/81500298-0dc8a300-92da-11ea-9a17-27ff4cfca133.png)

**Comment by meezaan** [comment]
OK, I've thought of an interim solution for this. I need a few days to test it out, but I'll keep you posted insha Allah as I make some progress.

**Comment by meezaan** [comment]
Salaam, I'm testing out some changes, but before publishing anything, I want to confirm if something like this will work:

![Screenshot 2020-05-12 at 12 47 08](https://user-images.githubusercontent.com/1839282/81662655-f19a4280-944e-11ea-8a4f-349499db1668.png)

**Comment by meezaan** [comment]
You can now pass the query parameter ?fontHack=true to your API calls to get the modified version. This way we are not making any incorrect grammatical changes to the text - but just modifying the output at runtime to use a singular madda instead of the laam, hamza and alif where they appear together. So once the deployment completes in 5 minutes or so, https://api.alquran.cloud/v1/ayah/2:4/quran-uthmani?fontHack=true should produce the desired result.

**Comment by vipafattal** [comment]
Amazing work @meezaan thank you, I'm thankful to you.

**Comment by meezaan** [comment]
Alhamdulillah

**Comment by meezaan** [comment]
Reopening as this may very well be a font display issue related to a proposal like https://www.unicode.org/L2/L2017/17377-proposal-tanwin-inline.html.

**Comment by vipafattal** [comment]
Salaam brother
I wont to let that I'm using [kitab-font](https://github.com/quranacademy/kitab-font) with quran-uthmani
with fontHack enabled with same results (وَبِٱلْءَاخِرَةِ) even the link you referenced (https://api.alquran.cloud/v1/ayah/2:4/quran-uthmani?fontHack=true) has same issue (see the attached image aya number 4).

![screenshot-2020-06-26_14 53 40 961](https://user-images.githubusercontent.com/22567094/85854537-3d196d80-b7bd-11ea-8213-6f79a23ee001.png)

**Comment by meezaan** [comment]
I will have a look - thank you for letting me know.

**Comment by meezaan** [comment]
@vipafattal I can see a bug in the code that I introduced when adding quran-unicode to the mix. I will patch it either today or tomorrow, inshaAllah!

**Comment by meezaan** [comment]
Should be fixed now.
