### ISSUE TITLE
Bismillahi rahmani raheem is different in two surah

### ISSUE THREAD

**Issue by rashnk** [islamic-network/api.alquran.cloud#40]
API end point : http://api.alquran.cloud/v1/quran/quran-uthmani

I was trying to remove bismillahirahmani raheem from the first ayath, I copied the arabic text from first Aya of  Sura 1. Fathiha

and wrote a function to replace with  blank text '', it replace bismi from all the first aya of all surah excepte sura 95 and 97

I checked the text  bismi in both sura and found there is difference in bismillahi rahmani raheem

Bismi in other surahs : **بِسْمِ**
Bismi in 95 and 97 : **بِّسْمِ**  

I request to please correct this,

**Comment by papasmile** [comment]
Assalaam alaykum wa rahmatullah,

Tasmiyya begins with shadda in Hafs?? mushaf in both 95 and 97 surahs, for example:

![Screen Shot 2020-07-02 at 10 46 54 AM](https://user-images.githubusercontent.com/3638363/86373451-6882d900-bc51-11ea-9606-d6624c335eab.png)

I am not a tajweed expert but I understand that it is due to 'baa' letter ending in previous surah (94 and 96), so for continuous reading tasmiyyah would be pronounced with shaddah.  Allah knows best

**Comment by rashnk** [comment]
you are right, but see the bismi in chapter 95 in quran in same site https://alquran.cloud/surah/95, there is no shaddah in bismi, but API returns it

**Comment by meezaan** [comment]
Salaam @rashnk yes, @papasmile is correct.

The bismillah on the web app has nothing to do with the the API, per se, and is hard coded up there. It does not change from Surah to Surah.

This is also, of course, specific to the Uthmani text. It certainly does not appear in some Turkish hand written editions of the Qur'an. I still need to check a sub-continent edition.

I'll close this issue.
