### ISSUE TITLE
Waqf displayed in the wrong place in surah/18/quran-uthmani

### ISSUE THREAD

**Issue by rashnk** [islamic-network/api.alquran.cloud#42]
API : http://api.alquran.cloud/v1/surah/18/quran-uthmani

 ۜ   waqf is displayed before the bismi 

![image](https://user-images.githubusercontent.com/12730428/86392636-6b191900-bcb9-11ea-8c0f-c00510640e66.png)

Correct place is at the end of the aya,, see screenshot from Tanzil quran
![image](https://user-images.githubusercontent.com/12730428/86392891-cf3bdd00-bcb9-11ea-90ce-9a0ca71fda9d.png)

**Comment by meezaan** [comment]
Al Salaamu Alaykum,

Thank you for all the issues you have been raising.

I am not sure if this is actually in the wrong place or just a result of the way text is displayed.

The problem does not exist with the font. There are several issues like this that have been identified, and they're all on the project board to be looked at.

I am working on a little tool to try it out with the various fonts. 

This can also be a result of the way certain utf8 encoded characters were parsed prior to 2016, and after a proposal the way they are parsed was changed - so the display changed, but it still works fine with some of the fonts (because I assume they were not updated).

The text was written before 2016 - this may explain some of the issues.

Can you try the quran-unicode edition and see if that also has the same problem(s).

I have been a busy at work these last few weeks so, unfortunately, have not been able to get to this, but insha Allah, I will in the coming days.

**Comment by meezaan** [comment]
@rashnk I think this is a result of the browser rendering JSON with the direction right-to-left. If you switch it to left-to-right, you will see that this is not a problem.

I'll leave the issue open for you to double check and confirm. Once the font tester tool is ready these kind of things will become much easier to debug.

**Comment by rashnk** [comment]
Va. salam Bro
you are correct @meezaan dir="rtl" fixes this issue, 
Thank you for the help

**Comment by meezaan** [comment]
Alhamdulillah.
