### ISSUE TITLE
Incorrect ayah characters 

### ISSUE THREAD

**Issue by Q8root** [islamic-network/api.alquran.cloud#43]
Referring to the following endpoint: http://api.alquran.cloud/v1/page/44/quran-uthmani
Ayah # 267
the incorrect ayah (ِإِبْرَٰهِۦمُ) it must be (إبراهيم)

**Comment by meezaan** [comment]
@Q8root. Not in the Uthmani editions, it does not appear the way you would think it would. Here's an actual image (you might want to see it against a white background) - https://cdn.islamic.network/quran/images/2_260.png.

**Comment by Q8root** [comment]
Please refer to the following sandbox:-
https://codesandbox.io/embed/dark-https-t4put?fontsize=14&hidenavigation=1&theme=dark
Ayah will appear like this :-

> وَإِذْ قَالَ إِبْرَٰهِۦمُ رَبِّ أَرِنِى كَيْفَ تُحْىِ ٱلْمَوْتَىٰ ۖ قَالَ أَوَلَمْ تُؤْمِن ۖ قَالَ بَلَىٰ وَلَٰكِن لِّيَطْمَئِنَّ قَلْبِى ۖ قَالَ فَخُذْ أَرْبَعَةًۭ مِّنَ ٱلطَّيْرِ فَصُرْهُنَّ إِلَيْكَ ثُمَّ ٱجْعَلْ عَلَىٰ كُلِّ جَبَلٍۢ مِّنْهُنَّ جُزْءًۭا ثُمَّ ٱدْعُهُنَّ يَأْتِينَكَ سَعْيًۭا ۚ وَٱعْلَمْ أَنَّ ٱللَّهَ عَزِيزٌ حَكِيمٌۭ

**Comment by meezaan** [comment]
It's not an issue. This is how the text appears in Uthmanic editions. You need to pick a font that can display this.

**Comment by meezaan** [comment]
You can compare editions on https://alquran.cloud/arabic-font-edition-tester?reference=267. Try quran-uthmani-quran-academy - that edition has been updated to accommodate changes to the way arabic characters are rendered post 2016. The quran-uthmani text was done before that.

I will close this issue because it's definitely not the way you have asked for it to appear - the text does not appear that way in Uthmanic editions (the way the name Ibrahim would normally be written).
